name: Post to BlueSky
on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  run:
    name: Post
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run
        env: 
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          ZPDIC_API_KEY: ${{ secrets.ZPDIC_API_KEY }}
        run: BSKY_PASSWORD=$BSKY_PASSWORD ZPDIC_API_KEY=$ZPDIC_API_KEY deno run --allow-read --allow-net --allow-env main.ts
